### ISSUE TITLE
Display Client Registry results in a table format with the location  specified if the patient was been in multiple locations

### ISSUE THREAD

**Issue by ckemar** [IsantePlus/openmrs-module-mpi-client#37]
Display Client Registry results in a table format with the location  specified if the patient was been in multiple locations

**Comment by pmanko** [comment]
The previous work that limited what search results are being displayed on the OpenMRS side: https://github.com/IsantePlus/openmrs-module-mpi-client/pull/21/files

We might have to revert / modify this logic to correctly show one entry per location where a patient was registered.
